version: 2

refs:
  docker: &docker
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

jobs:
  build:
    <<: *docker

    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

      - run:
          command: |
            mkdir test-reports
            pipenv run pytest --junitxml=test-reports/junit.xml

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Run Docker Compose
          command: |
            docker-compose build

      - run:
          name: Push Docker Image
          command: echo 'TODO-push by branch'

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: tr1

  deploy-prod:
    <<: *docker
    steps:
      - checkout
      - run:
          command: echo 'TODO'

  deploy-dev:
    <<: *docker
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh

      - run:
          name: Deploy to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
