version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: cci-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: cci-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/bin/python3.6/site-packages"
      - run:
          command: |
            pipenv run "pytest"
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          command: |
            docker-compose build
            docker-compose up -d

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-impl
